### ISSUE TITLE
Add support for COM3D 2.5

### ISSUE THREAD

**Issue by habeebweeb** [habeebweeb/MeidoPhotoStudio#69]
This issue supersedes issue #54.

Adding support for com3d2.5 entails adding support for the new KC (fka CR) edit body and male body added in x0 dlc as well as fixing IK issues mentioned in #54 for regular maid body.

_Originally posted on 2022-04-11T20:33:33+02:00 (last updated on 2022-09-02T20:27:19+02:00)._

**Comment by habeebweeb** [comment]
Here's a list of things that need to be done. Might need to open up some new issues.

TODO:
- [x] Fix IK not working #54
- [ ] Add edit mode integrations
  - [ ] Add support for changing edit mode maid from non-KC maid to KC body maid
  - [ ] Fix IK breaking when changing body type #67
- [ ] Support x0 male body #74

_Originally posted on 2022-09-01T02:20:52+02:00 (last updated on 2022-09-02T20:23:00+02:00)._
